# Define the name of the GitHub Action workflow
name: ECS Cluster Deploy Drupal

# This workflow is manually triggered using the GitHub Actions UI
on:
  workflow_dispatch:
    # Define inputs that are required for the manual trigger
    inputs:
      cluster_name:
        description: 'Name of the ECS Cluster'  # Name of the EC2 instance
        required: true  # This input is required
      region:
        description: 'AWS region for the instance'  # AWS region where the instance will be created
        required: true  # This input is required
      # instanceType:
      #   description: 'AWS instance type'  # Type of the EC2 instance (e.g., t2.micro)
      #   required: true  # This input is required
      action:
        description: 'Action to perform (apply/destroy)'  # Action to be performed (create or delete the instance)
        required: true  # This input is required
      port_context:
        description: "port_context"
        required: true

# Jobs to be executed in this workflow
jobs:
  # Job for applying the EC2 instance
  apply-ecs-cluster:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Execute this job only if the action input is "apply"
    if: ${{ github.event.inputs.action == 'apply' }}

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4


      - name: UPSERT Entity
        uses: port-labs/port-github-action@v1
        with:
          identifier: ${{ fromJson(inputs.port_context).entity }}
          blueprint: service
          properties: |-
            {
              "title": "Cluster_Name_{{ github.event.inputs.cluster_name }}",
              "Title": "Cluster_Name_{{ github.event.inputs.cluster_name }}",
              "Identifier": "Cluster_Name_{{ github.event.inputs.cluster_name }}",
              "resource_definitions": "${{ github.server_url }}/${{ github.repository_owner }}/${{ fromJson(inputs.port_context).entity }}/blob/main/resources/"
            }
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          runId: ${{ fromJson(inputs.port_context).runId }}

      - name: Create a log message (apply)
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: "Initiating creation of ECS cluster: ${{ github.event.inputs.cluster_name }}."

            # Configure AWS credentials. Please store the value of these keys in GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: .  # Assuming your Terraform files are in the root directory

      # Format Terraform code
      - name: Terraform Format
        run: terraform fmt
        working-directory: .

      # Validate the Terraform code
      - name: Terraform Validate
        run: terraform validate
        working-directory: .

      # Apply the Terraform plan to create the EC2 instance
      - name: Terraform Apply
        run: terraform apply -var cluster_name=${{ github.event.inputs.cluster_name }} -var region=${{ github.event.inputs.region }} -auto-approve
        working-directory: .


  # Job for destroying the EC2 instance
  destroy-ecs-cluster:
    runs-on: ubuntu-latest
    
    # Execute this job only if the action input is "destroy"
    if: ${{ github.event.inputs.action == 'destroy' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: UPSERT Entity
        uses: port-labs/port-github-action@v1
        with:
          identifier: ${{ fromJson(inputs.port_context).entity }}
          blueprint: service
          properties: |-
            {
              "resource_definitions": "${{ github.server_url }}/${{ github.repository_owner }}/${{ fromJson(inputs.port_context).entity }}/blob/main/resources/"
            }
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          runId: ${{ fromJson(inputs.port_context).runId }}

      - name: Create a log message (apply)
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: "Initiating Destruction of ECS cluster: ${{ github.event.inputs.cluster_name }}."

      # Configure AWS credentials. Please store the value of these keys in GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}
        
      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: .
      
      # Format Terraform code
      - name: Terraform Format
        run: terraform fmt
        working-directory: .
      - name: Run Terraform Plan
        run: |
          terraform init
          terraform plan -var cluster_name=${{ github.event.inputs.cluster_name }} -var region=${{ github.event.inputs.region }} -out=tfplan
          terraform show -json tfplan > tfplan.json

      # Destroy the resources managed by Terraform
      - name: Terraform Destroy
        run: terraform destroy -var cluster_name=${{ github.event.inputs.cluster_name }} -var region=${{ github.event.inputs.region }} -auto-approve
        working-directory: .

      - name: Inform Port about the status of the ECS cluster destruction
        if: ${{ github.event.inputs.action == 'destroy' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          status: "SUCCESS"
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: "ECS cluster destruction has been completed: ${{ github.event.inputs.cluster_name }}"
